### ISSUE TITLE
Include data format version number in metadata

### ISSUE THREAD

**Issue by lwthatcher** [byuhci/BDLT#2]
Somehow include the BDL data format version number with the file, so our parsers know how to parse it properly. This should also include information about the tick rate if possible.

This can be done in our current format using the `syslog` token or something like that if needs be:
```
S, 0, version=legacy-0.2
S, 0, tps=1000
...
```

- [ ] Include Version
- [x] Include ticks-per-second rate

**Comment by krs013** [comment]
I've added a script called ticks2ms.py that will copy a data file in the old format and convert the times into milliseconds. The default tag for specifying that it is in milliseconds is "D,Time:0ms" which indicates the unit (ms) and the starting point (0) for time stamps in that file. The D tag is one I'd like to work in for messages pertinent to the data stream but that aren't so trivial as normal log messages (L). We currently don't have any job for S; it probably won't be in future data files.

**Comment by krs013** [comment]
The parameters are configurable, if a different tag (or no tag) suits it better. It can also be hijacked to back-convert data for *temporary purposes* by inverting the number that is used for the conversion. If the source file already has a spec for the time stamps, however, it won't remove it. That functionality shouldn't be needed anyway, in the long run.

**Comment by krs013** [comment]
Also I'm using "tag" wrong, I'm going to change that in the code to... spec?

**Comment by krs013** [comment]
And now bdlbin.py will include that same message in anything that it decodes. If that works, @lwthatcher, then this issue should be ready for closing.

**Comment by lwthatcher** [comment]
I'll take a look at it, thanks!

**Comment by lwthatcher** [comment]
Any chance, however, that you could provide a list of the changes/differences between this version of the BDL and the previous version(s)?

**Comment by krs013** [comment]
Just here on the thread, or do you mean something else? (Actually, that would be a good thing for me to put in the README… so maybe I’ll do that)

**Comment by lwthatcher** [comment]
I'll make a new issue, ~~just for fun~~ for convenience.

**Comment by krs013** [comment]
If you do, consider closing this one please :)

**Comment by lwthatcher** [comment]
I looked over your code and it looks that tick-rate part should be solid.

Can we include the BDL version number in the header tags as well? I noticed you have a `0.1` release for the old code, can you name this version as well and include that in another `D` tag?

**Comment by krs013** [comment]
It would be misleading—the BDL doesn’t write anything directly to text like before, and everything that goes to VAT as text passes through the decoder. I intend to have some kind of version indication in the BDL stream, but it will be a little more nuanced than that, probably. In any event, I don’t think it would be useful to the CSV file, as I hope it doesn’t exist long enough to see another version.

**Comment by lwthatcher** [comment]
The fist line `D, 0:ms` is sufficient for recognizing between old and new data for now. Until told otherwise, this is the standard I am going to follow for determining tick-rate in VAT.
